APIVersion: v1.11.1
name: refactor-it
type: php
docroot: ""
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: "Europe/Amsterdam"
mailhog_port: 8300
omit_containers:
  - db
  - dba