name: refactor-it
type: php
docroot: ""
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: true
provider: default
use_dns_when_possible: false
timezone: "Europe/Amsterdam"
omit_containers:
  - db
  - dba
